create table if not exists public.events (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  city_id bigint not null references public.cities(id),
  title text not null check (char_length(btrim(title)) between 3 and 160),
  description text not null default '' check (char_length(description) <= 2500),
  category text not null default 'outros' check (category in ('musica','gastronomia','feira','esporte','cultura','inauguracao','infantil','outros')),
  banner_path text not null check (char_length(banner_path) between 5 and 512),
  venue_name text not null check (char_length(btrim(venue_name)) between 2 and 160),
  venue_address text not null check (char_length(btrim(venue_address)) between 5 and 300),
  starts_at timestamptz not null,
  ends_at timestamptz,
  utc_offset text not null default '-03:00' check (utc_offset in ('-02:00','-03:00','-04:00','-05:00')),
  free_entry boolean not null default true,
  ticket_price_cents integer,
  ticket_url text check (ticket_url is null or (char_length(ticket_url) <= 500 and ticket_url ~* '^https://[^[:space:]]+$')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint events_end_after_start check (ends_at is null or ends_at > starts_at),
  constraint events_price_consistency check ((free_entry and ticket_price_cents is null) or (not free_entry and ticket_price_cents is not null and ticket_price_cents > 0))
);
create index if not exists events_public_feed_idx on public.events (city_id, starts_at, id) where is_active = true;
create index if not exists events_organizer_idx on public.events (business_id, starts_at desc);
alter table public.events enable row level security;
create policy events_public_read on public.events for select to anon, authenticated using (
  is_active and coalesce(ends_at,starts_at) >= now()
  and exists (
    select 1 from public.businesses b where b.id=business_id
      and b.listing_type='business' and b.publication_status='published'
      and b.is_active and not b.billing_suspended
  )
);
create policy events_owner_read on public.events for select to authenticated using (
  exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid()))
);
create policy events_owner_insert on public.events for insert to authenticated with check (
  exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())
    and b.listing_type='business' and b.city_id=city_id and b.is_active and not b.billing_suspended)
);
create policy events_owner_update on public.events for update to authenticated using (
  exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid()) and b.listing_type='business')
) with check (
  exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid())
    and b.listing_type='business' and b.city_id=city_id and b.is_active and not b.billing_suspended)
);
create policy events_owner_delete on public.events for delete to authenticated using (
  exists (select 1 from public.businesses b where b.id=business_id and b.owner_id=(select auth.uid()) and b.listing_type='business')
);
create policy events_admin_manage on public.events for all to authenticated using (
  (select private.is_admin())
) with check ((select private.is_admin()));
grant select on public.events to anon;
grant select, insert, update, delete on public.events to authenticated;
grant usage, select on sequence public.events_id_seq to authenticated;
comment on table public.events is 'Eventos criados por comerciantes vinculados a vitrines reivindicadas. Horarios exibidos conforme utc_offset; publico ve somente eventos atuais de vitrines ativas.';